### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by adamdport** [Nyx0uf/qlwoff#2]
You include instructions to install `freetype`, but instructions on installing qlwoff are missing.

**Comment by Nyx0uf** [comment]
Like every quicklook plugins, in the QuickLook folder. ~/Library/QuickLook or /Library/QuickLook

**Comment by nkgm** [comment]
I think the right question would be: is there a compiled version available?
Please consider making this available as it looks like a little more than a simple clone-and-build.
